-- This doesn't seem to work, not 100% sure why. I've just disabled the Markdown extra so most of the rubbish disappears and I'll leave this here to come back to later if I decide to.
return {
--   {
--     "MeanderingProgrammer/render-markdown.nvim",
--     opts = {
--       code = {
--         enable = false,
--       },
--       link = {
--         enable = false,
--       },
--       heading = {
--         sign = false,
--         icons = {},
--       },
--       checkbox = {
--         enabled = false,
--       },
--     },
--   },
}
