require("config.options")
require("config.pack")
require("config.colorscheme")
require("config.autocmds")

require("plugins.mason")
require("plugins.dap")
require("plugins.autopairs")
require("plugins.lazydev")
require("plugins.blink")
require("plugins.conform")
require("plugins.flash")
require("plugins.gitsigns")
require("plugins.grug-far")
require("plugins.lint")
require("plugins.lualine")
require("plugins.mini-icons")
require("plugins.neotest")
require("plugins.snacks")
require("plugins.surround")
require("plugins.todo-comments")
require("plugins.treesitter")
require("plugins.ts-comments")
require("plugins.which-key")
require("plugins.rustaceanvim")

-- After Snacks.setup so keymaps that require("snacks") see a configured instance.
require("config.keymaps")

require("lsp")
require("lsp.keymaps")
