local Snacks = require("snacks")
local map = require("config.map")

map("n", "<leader>ch", function()
	vim.cmd("checkhealth")
end, "Check health")

-- buffers (from LazyVim)
map("n", "<S-h>", "<cmd>bprevious<cr>", "Prev Buffer")
map("n", "<S-l>", "<cmd>bnext<cr>", "Next Buffer")
map("n", "[b", "<cmd>bprevious<cr>", "Prev Buffer")
map("n", "]b", "<cmd>bnext<cr>", "Next Buffer")
map("n", "<leader>bb", "<cmd>e #<cr>", "Switch to Other Buffer")
map("n", "<leader>`", "<cmd>e #<cr>", "Switch to Other Buffer")
map("n", "<leader>bd", function()
	Snacks.bufdelete()
end, "Delete Buffer")
map("n", "<leader>bo", function()
	Snacks.bufdelete.other()
end, "Delete Other Buffers")
map("n", "<leader>bi", function()
	Snacks.bufdelete.invisible()
end, "Delete Invisible Buffers")
map("n", "<leader>bD", "<cmd>:bd<cr>", "Delete Buffer and Window")

-- Be a good little vimmer
map("n", "<left>", function()
	vim.notify("Use h to move left!", vim.log.levels.WARN, { title = "Navigation Hint" })
end)
map("n", "<right>", function()
	vim.notify("Use l to move right!", vim.log.levels.WARN, { title = "Navigation Hint" })
end)
map("n", "<up>", function()
	vim.notify("Use k to move up!", vim.log.levels.WARN, { title = "Navigation Hint" })
end)
map("n", "<down>", function()
	vim.notify("Use j to move down!", vim.log.levels.WARN, { title = "Navigation Hint" })
end)
