require("config.plugins.completion")
require("config.plugins.ui")
require("config.plugins.comment")
require("config.plugins.picker")
require("config.plugins.conform")
require("config.plugins.treesitter")
require("config.plugins.git")
require("config.plugins.neotest")
